// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armapicenter

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
)

// ClientFactory is a client factory used to create any client in this module.
// Don't use this type directly, use NewClientFactory instead.
type ClientFactory struct {
	internal *arm.Client
}

// NewClientFactory creates a new instance of ClientFactory with the specified values.
// The parameter values will be propagated to any client created from this factory.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - pass nil to accept the default values.
func NewClientFactory(options *arm.ClientOptions) (*ClientFactory, error) {
	internal, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	return &ClientFactory{
		internal: internal,
	}, nil
}

// NewAPIDefinitionsClient creates a new instance of APIDefinitionsClient.
func (c *ClientFactory) NewAPIDefinitionsClient() *APIDefinitionsClient {
	return &APIDefinitionsClient{
		internal: c.internal,
	}
}

// NewAPIVersionsClient creates a new instance of APIVersionsClient.
func (c *ClientFactory) NewAPIVersionsClient() *APIVersionsClient {
	return &APIVersionsClient{
		internal: c.internal,
	}
}

// NewApisClient creates a new instance of ApisClient.
func (c *ClientFactory) NewApisClient() *ApisClient {
	return &ApisClient{
		internal: c.internal,
	}
}

// NewDeletedServicesClient creates a new instance of DeletedServicesClient.
func (c *ClientFactory) NewDeletedServicesClient() *DeletedServicesClient {
	return &DeletedServicesClient{
		internal: c.internal,
	}
}

// NewDeploymentsClient creates a new instance of DeploymentsClient.
func (c *ClientFactory) NewDeploymentsClient() *DeploymentsClient {
	return &DeploymentsClient{
		internal: c.internal,
	}
}

// NewEnvironmentsClient creates a new instance of EnvironmentsClient.
func (c *ClientFactory) NewEnvironmentsClient() *EnvironmentsClient {
	return &EnvironmentsClient{
		internal: c.internal,
	}
}

// NewMetadataSchemasClient creates a new instance of MetadataSchemasClient.
func (c *ClientFactory) NewMetadataSchemasClient() *MetadataSchemasClient {
	return &MetadataSchemasClient{
		internal: c.internal,
	}
}

// NewOperationsClient creates a new instance of OperationsClient.
func (c *ClientFactory) NewOperationsClient() *OperationsClient {
	return &OperationsClient{
		internal: c.internal,
	}
}

// NewServicesClient creates a new instance of ServicesClient.
func (c *ClientFactory) NewServicesClient() *ServicesClient {
	return &ServicesClient{
		internal: c.internal,
	}
}

// NewWorkspacesClient creates a new instance of WorkspacesClient.
func (c *ClientFactory) NewWorkspacesClient() *WorkspacesClient {
	return &WorkspacesClient{
		internal: c.internal,
	}
}
