// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armtest

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
)

// ClientFactory is a client factory used to create any client in this module.
// Don't use this type directly, use NewClientFactory instead.
type ClientFactory struct {
	internal *arm.Client
}

// NewClientFactory creates a new instance of ClientFactory with the specified values.
// The parameter values will be propagated to any client created from this factory.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - pass nil to accept the default values.
func NewClientFactory(options *arm.ClientOptions) (*ClientFactory, error) {
	internal, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	return &ClientFactory{
		internal: internal,
	}, nil
}

// NewBodyRootsClient creates a new instance of BodyRootsClient.
func (c *ClientFactory) NewBodyRootsClient() *BodyRootsClient {
	return &BodyRootsClient{
		internal: c.internal,
	}
}

// NewLROClient creates a new instance of LROClient.
func (c *ClientFactory) NewLROClient() *LROClient {
	return &LROClient{
		internal: c.internal,
	}
}

// NewParameterGroupOperationsClient creates a new instance of ParameterGroupOperationsClient.
func (c *ClientFactory) NewParameterGroupOperationsClient() *ParameterGroupOperationsClient {
	return &ParameterGroupOperationsClient{
		internal: c.internal,
	}
}
